project.name=start

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ddd
spring.datasource.username=postgre
spring.datasource.password=123456
