package com.lzb.demo.common.enums;

import com.lzb.demo.common.utils.enums.EnumValue;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Currency implements EnumValue<String> {
    AED("AED", "阿联酋迪拉姆"),
    AFN("AFN", "Afghan afghani"),
    ALL("ALL", "Albanian lek"),
    AMD("AMD", "Armenian dram"),
    ANG("ANG", "Netherlands Antillean guilder"),
    AOA("AOA", "Angolan kwanza"),
    ARS("ARS", "Argentine peso"),
    AUD("AUD", "澳元"),
    AWG("AWG", "Aruban florin"),
    AZN("AZN", "Azerbaijani manat"),
    BAM("BAM", "Bosnia and Herzegovina convertible mark"),
    BBD("BBD", "Barbados dollar"),
    BDT("BDT", "Bangladeshi taka"),
    BGN("BGN", "Bulgarian lev"),
    BHD("BHD", "Bahraini dinar"),
    BIF("BIF", "Burundian franc"),
    BMD("BMD", "Bermudian dollar"),
    BND("BND", "Brunei dollar"),
    BOB("BOB", "Boliviano"),
    BOV("BOV", "Bolivian Mvdol"),
    BRL("BRL", "巴西里亚尔"),
    BSD("BSD", "Bahamian dollar"),
    BTN("BTN", "Bhutanese ngultrum"),
    BWP("BWP", "Botswana pula"),
    BYN("BYN", "Belarusian ruble"),
    BZD("BZD", "Belize dollar"),
    CAD("CAD", "加元"),
    CDF("CDF", "Congolese franc"),
    CHE("CHE", "WIR euro"),
    CHF("CHF", "瑞士法郎"),
    CHW("CHW", "WIR franc"),
    CLF("CLF", "Unidad de Fomento"),
    CLP("CLP", "Chilean peso"),
    COP("COP", "Colombian peso"),
    COU("COU", "Unidad de Valor Real"),
    CRC("CRC", "Costa Rican colon"),
    CUC("CUC", "Cuban convertible peso"),
    CUP("CUP", "Cuban peso"),
    CVE("CVE", "Cape Verdean escudo"),
    CZK("CZK", "Czech koruna"),
    DJF("DJF", "Djiboutian franc"),
    DKK("DKK", "丹麦克朗"),
    DOP("DOP", "Dominican peso"),
    DZD("DZD", "Algerian dinar"),
    EGP("EGP", "Egyptian pound"),
    ERN("ERN", "Eritrean nakfa"),
    ETB("ETB", "Ethiopian birr"),
    EUR("EUR", "欧元"),
    FJD("FJD", "Fiji dollar"),
    FKP("FKP", "Falkland Islands pound"),
    GBP("GBP", "英镑"),
    GEL("GEL", "Georgian lari"),
    GHS("GHS", "Ghanaian cedi"),
    GIP("GIP", "Gibraltar pound"),
    GMD("GMD", "Gambian dalasi"),
    GNF("GNF", "Guinean franc"),
    GTQ("GTQ", "Guatemalan quetzal"),
    GYD("GYD", "Guyanese dollar"),
    HKD("HKD", "港元"),
    HNL("HNL", "Honduran lempira"),
    HRK("HRK", "Croatian kuna"),
    HTG("HTG", "Haitian gourde"),
    HUF("HUF", "Hungarian forint"),
    IDR("IDR", "印尼卢比"),
    ILS("ILS", "以色列新谢克尔"),
    INR("INR", "印度卢比"),
    IQD("IQD", "Iraqi dinar"),
    IRR("IRR", "Iranian rial"),
    ISK("ISK", "Icelandic króna"),
    JMD("JMD", "Jamaican dollar"),
    JOD("JOD", "Jordanian dinar"),
    JPY("JPY", "日元"),
    KES("KES", "Kenyan shilling"),
    KGS("KGS", "Kyrgyzstani som"),
    KHR("KHR", "Cambodian riel"),
    KMF("KMF", "Comoro franc"),
    KPW("KPW", "North Korean won"),
    KRW("KRW", "韩元"),
    KWD("KWD", "Kuwaiti dinar"),
    KYD("KYD", "Cayman Islands dollar"),
    KZT("KZT", "Kazakhstani tenge"),
    LAK("LAK", "Lao kip"),
    LBP("LBP", "Lebanese pound"),
    LKR("LKR", "Sri Lankan rupee"),
    LRD("LRD", "Liberian dollar"),
    LSL("LSL", "Lesotho loti"),
    LYD("LYD", "Libyan dinar"),
    MAD("MAD", "Moroccan dirham"),
    MDL("MDL", "Moldovan leu"),
    MGA("MGA", "Malagasy ariary"),
    MKD("MKD", "Macedonian denar"),
    MMK("MMK", "Myanmar kyat"),
    MNT("MNT", "Mongolian tögrög"),
    MOP("MOP", "澳门元"),
    MRU("MRU", "Mauritanian ouguiya"),
    MUR("MUR", "Mauritian rupee"),
    MVR("MVR", "Maldivian rufiyaa"),
    MWK("MWK", "Malawian kwacha"),
    MXN("MXN", "墨西哥比索"),
    MXV("MXV", "Mexican Unidad de Inversion"),
    MYR("MYR", "林吉特"),
    MZN("MZN", "Mozambican metical"),
    NAD("NAD", "Namibian dollar"),
    NGN("NGN", "Nigerian naira"),
    NIO("NIO", "Nicaraguan córdoba"),
    NOK("NOK", "挪威克朗"),
    NPR("NPR", "Nepalese rupee"),
    NZD("NZD", "新西兰元"),
    OMR("OMR", "Omani rial"),
    PAB("PAB", "Panamanian balboa"),
    PEN("PEN", "Peruvian sol"),
    PGK("PGK", "Papua New Guinean kina"),
    PHP("PHP", "菲律宾比索"),
    PKR("PKR", "Pakistani rupee"),
    PLN("PLN", "波兰兹罗提"),
    PYG("PYG", "Paraguayan guaraní"),
    QAR("QAR", "Qatari riyal"),
    RON("RON", "罗马尼亚列伊"),
    RSD("RSD", "Serbian dinar"),
    CNY("CNY", "人民币"),
    RUB("RUB", "卢布"),
    RWF("RWF", "Rwandan franc"),
    SAR("SAR", "沙特里亚尔"),
    SBD("SBD", "Solomon Islands dollar"),
    SCR("SCR", "Seychelles rupee"),
    SDG("SDG", "Sudanese pound"),
    SEK("SEK", "瑞典克朗"),
    SGD("SGD", "新加坡元"),
    SHP("SHP", "Saint Helena pound"),
    SLL("SLL", "Sierra Leonean leone"),
    SLE("SLE", "Sierra Leonean leone"),
    SOS("SOS", "Somali shilling"),
    SRD("SRD", "Surinamese dollar"),
    SSP("SSP", "South Sudanese pound"),
    STN("STN", "São Tomé and Príncipe dobra"),
    SVC("SVC", "Salvadoran colón"),
    SYP("SYP", "Syrian pound"),
    SZL("SZL", "Swazi lilangeni"),
    THB("THB", "泰国铢"),
    TJS("TJS", "Tajikistani somoni"),
    TMT("TMT", "Turkmenistan manat"),
    TND("TND", "Tunisian dinar"),
    TOP("TOP", "Tongan paʻanga"),
    TRY("TRY", "土耳其里拉"),
    TTD("TTD", "Trinidad and Tobago dollar"),
    TWD("TWD", "新台币"),
    TZS("TZS", "Tanzanian shilling"),
    UAH("UAH", "Ukrainian hryvnia"),
    UGX("UGX", "Ugandan shilling"),
    USD("USD", "美元"),
    USN("USN", "United States dollar"),
    UYI("UYI", "Uruguay Peso en Unidades Indexadas"),
    UYU("UYU", "Uruguayan peso"),
    UYW("UYW", "Unidad previsional[16]"),
    UZS("UZS", "Uzbekistan som"),
    VED("VED", "Venezuelan bolívar digital[17]"),
    VES("VES", "Venezuelan bolívar soberano[13]"),
    VND("VND", "Vietnamese đồng"),
    VUV("VUV", "Vanuatu vatu"),
    WST("WST", "Samoan tala"),
    XAF("XAF", "CFA franc BEAC"),
    XAG("XAG", "Silver"),
    XAU("XAU", "Gold"),
    XBA("XBA", "European Composite Unit"),
    XBB("XBB", "European Monetary Unit"),
    XBC("XBC", "European Unit of Account 9"),
    XBD("XBD", "European Unit of Account 17"),
    XCD("XCD", "East Caribbean dollar"),
    XDR("XDR", "Special drawing rights"),
    XOF("XOF", "CFA franc BCEAO"),
    XPD("XPD", "Palladium"),
    XPF("XPF", "CFP franc"),
    XPT("XPT", "Platinum"),
    XSU("XSU", "SUCRE"),
    XTS("XTS", "Code reserved for testing"),
    XUA("XUA", "ADB Unit of Account"),
    XXX("XXX", "No currency"),
    YER("YER", "Yemeni rial"),
    ZAR("ZAR", "南非兰特"),
    ZMW("ZMW", "Zambian kwacha"),
    ZWL("ZWL", "Zimbabwean dollar"),
    ;

    private final String value;
    private final String desc;

}